cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'caskroom/versions'

brew 'ack'
brew 'coreutils'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'sqlite'
brew 'heroku'
brew 'python3'

cask 'google-chrome'
cask 'karabiner'
cask 'dash'
cask 'iterm2'
cask 'alfred'
cask 'keka'
cask 'skype'
cask 'slack'
cask 'gitkraken'
cask 'postico'
cask 'sublime-text3'
cask 'transmission'
cask 'vlc'
